# Definindo versão do Docker Compose
version: '3.8'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./rest-api-ezops-test
      dockerfile: Dockerfile
    container_name: rest-api
    ports:
      - "3000:3000"
    volumes:
      - ./rest-api-ezops-test:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./vuejs-ezops-test
      dockerfile: Dockerfile
    container_name: vuejs
    ports:
      - "8080:8080"
    volumes:
      - ./vuejs-ezops-test:/app
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
